02_semaphore_prodcons: 02_semaphore_prodcons.c
	gcc -o 02_semaphore_prodcons 02_semaphore_prodcons.c -lpthread -g
03_condvar_prodcons: 03_condvar_prodcons.c
	gcc -o 03_condvar_prodcons 03_condvar_prodcons.c -lpthread -g
04_lockfree_queue: 04_lockfree_queue.c
	gcc -o 04_lockfree_queue 04_lockfree_queue.c -lpthread -g
clean:
	rm -f 02_semaphore_prodcons 03_condvar_prodcons 04_lockfree_queue
